---

- name: 'Install the OpenTelemetry demo application'
  hosts: 'k3s1'
  gather_facts: true
  become: false
  module_defaults:
    kubernetes.core.helm:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s:
      kubeconfig: './k3s-kubeconfig'
    kubernetes.core.k8s_info:
      kubeconfig: './k3s-kubeconfig'

  tasks:

    - name: 'Install the OpenTelemetry demo application via the helm chart'
      delegate_to: 'localhost'
      kubernetes.core.helm:
        chart_repo_url: 'https://open-telemetry.github.io/opentelemetry-helm-charts'
        release_name: 'opentelemetry-demo'
        chart_ref: 'opentelemetry-demo'
        release_namespace: 'default'
        release_values:
          components:
            frontendProxy:
              ingress:
                enabled: true
                hosts:
                  - host: "demo.{{ hostvars['k3s1']['ansible_default_ipv4']['address'] }}.sslip.io"
                    paths:
                      - path: /
                        pathType: Prefix
                        port: 8080
